### ISSUE TITLE
Autobouquetswiki not updated

### ISSUE THREAD

**Issue by jimbo2018** [LraiZer/AutoBouquetsWiki#4]
Hi. Hope you can restart the wiki asbit has nit updated fir around a week or more.

It has stopped posting to the commando website 

Hope this can be sorted. Thanks

**Comment by LraiZer** [comment]
Been out of the country and network cable had been pulled out by mistake. Missing days have been uploaded.

**Comment by jimbo2018** [comment]
Thank you. The ukcvs forum may have disappeared too. Thank you for sorting it
